POST http://localhost:8080/insertProducts
Content-Type: application/json

{
  "warehouseName": "Warehouse 1",
  "quantity": 1,
  "product": {
    "sku": "SKU-1",
    "name": "Product 1",
    "price": 12,
    "type": "Book",
    "author": "Arthur Author"
  }
}